### PR TITLE
Fix/join leave events spam race condition & add owned events listener

### LINKED ISSUE #404: Owned event updates are not reflected in the UI
## Description
When a user edits an event that they own (for example changing the title), the modification is not reflected in the app UI in real-time. The state controller only listens to joined and saved events, but does not listen to owned events. This means updates made by the event creator are not propagated to the UI unless a hard refresh or reload happens.

## Steps to reproduce
Open the bottom sheet and go to the owned events tab
Modify the title of an event
Return to the owned event list view

### Current behavior
The event still displays the old title and outdated information.

### Expected behavior
Changes to owned events should be reflected immediately in the UI via a real-time listener, just like joined and saved events.

### LINKED ISSUE #405: Rapid clicking on Join/Save causes inconsistent event state
## Description
Spamming the Join or Save button can desynchronize the local state from the backend state. Because the UI uses both manual fetches (e.g. getSavedEvents/getJoinedEvents) and live listeners, rapid toggling leads to race conditions and sometimes the event ends up in neither state (not joined and not available to join, or not saved and not saveable).

## Steps to reproduce
Open the details of an event you have not joined/saved
Quickly tap the Join or Save button multiple times
Navigate to the bottom sheet and check the events lists

### Current behavior
The event is sometimes:
Marked as joined in the detailed sheet but not in the list of joined events
Clicking on joining/leaving won't have any effect anymore

### Expected behavior
Rapid taps should be debounced or ignored, and the event should always end in a consistent state:
Only one source of truth should be used (preferably the real-time listener).

### PR DESCRIPTION
**Pull request by e-bernier**
## Description
This PR fixes two critical real-time synchronization issues and removes a deprecated UI feature:

- Adds real-time listening for **owned events** so that when a user edits an event they created (title, date, location, etc.), the change is immediately reflected across the app without requiring a manual refresh.
- Eliminates race conditions and desynchronization caused by spamming Join/Save/Unsave buttons by:
  - Removing all manual initial fetches (`getSavedEvents`, `getJoinedEvents`, etc.)
  - Making the real-time listeners emit the initial state as "added" events
  - Adding simple anti-spam debouncing (500 ms per event)
- Removes the unused "Top Categories" section from the map search bottom sheet (UI + tests).

**Related Issue:**  
Closes #404
Closes #405

---

## Changes

**Implementation:**
- Added `listenToOwnedEvents` + `ownedEvents` state in `MapEventStateController`
- Refactored `listenToUserEvents` logic: first snapshot per event is now treated as "added", subsequent ones as "modified"
- Removed all initial `loadSavedEvents()`, `loadJoinedEvents()`, `loadOwnedEvents()` calls from `refreshEventsList()` and `init`
- Introduced anti-spam guard (`isSpamming`) that ignores repeated actions on the same event within 500 ms
- Optimistic join now correctly adds the user ID to `participantIds` locally
- Cleaned up `BottomSheetContent` and `MapScreen`: removed `topCategories` and `onCategoryClick` props

**Tests:**
- Updated `EventRepositoryFirestoreTest` with new owned-events listener tests and removal detection
- Updated `MapEventStateControllerTest`:
  - `refreshEventsList` now only refreshes filtered events
  - Added owned-events listener verification
  - Added anti-spam protection test
- Removed obsolete "Top Categories" UI tests
- Fixed flaky date assertions in `MemoryFormScreenTest`

---

## Testing
- [x] Unit tests pass
- [x] Instrumentation tests pass
- [x] Manual testing completed
- [x] Coverage maintained (≥80%)

**Test summary:**  
Added/updated 8 unit tests covering owned-event real-time sync, event removal detection, and anti-spam behavior. All existing join/leave/save flows now rely solely on listeners.

---

## Screenshots/Videos

---

## Checklist
- [x] Sufficient documentation and minimal inline comments
- [x] All tests passing
- [x] No new warnings
- [x] If related issue exists: issue has all labels, fields, and milestone filled

### CODE REVIEW

File: app/src/androidTest/java/com/swent/mapin/ui/map/BottomSheetContentTest.kt [hunk 1]
```diff
@@ -141,11 +141,9 @@ class BottomSheetContentTest {
                   onSubmit = onSubmit),
           isSearchMode = true,
           recentItems = recentItems,
-          topCategories = topCategories,
           searchResults = searchResults,
           onRecentSearchClick = onRecentSearchClick,
           onRecentEventClick = onRecentEventClick,
-          onCategoryClick = onCategoryClick,
```
Comment (naderbahri) [inline app/src/androidTest/java/com/swent/mapin/ui/map/BottomSheetContentTest.kt]: **Question**: Removed topCategories parameter from SearchModeContent call but some tests and callers were also removed. Confirm the removal is intentional and document the API change in the PR description so downstream call sites or consumers can be updated predictably.

File: app/src/main/java/com/swent/mapin/model/event/EventRepository.kt [hunk 2]
```diff
@@ -114,12 +114,11 @@ interface EventRepository {
...
-   *   removed after registration.
-   * - To get the current state, call getSavedEvents(userId) separately before or after registering
-   *   this listener.
+   *   removed after registration. However it is used in such a way it first consider that there are
+   *   no event at first so all events already in the user's saved events are considered as new.
+   * - There should no longer be any need for getSavedEvents(userId) separately before or after
+   *   registering this listener.
    *
    * Callback details:
    * - Callbacks are delivered on a Firestore background thread (not the Android main thread).
```
Comment (naderbahri) [inline app/src/main/java/com/swent/mapin/model/event/EventRepository.kt]: **Nitpick**: The documentation now contains mixed wording about initial emissions and usage assumptions. Make the contract explicit and unambiguous. State precisely whether the first callback may contain the existing items as "added" and whether callers must call getOwnedEvents/getSavedEvents for initial state. Clear deterministic behavior improves implementer and consumer expectations.

File: app/src/main/java/com/swent/mapin/ui/map/MapScreen.kt [hunk 3]
```diff
@@ -525,7 +525,6 @@ fun MapScreen(
                       event = selectedEvent,
                       sheetState = viewModel.bottomSheetState,
                       isParticipating = viewModel.joinedEvents.any { it.uid == selectedEvent.uid },
-                      // Use viewModel.savedEvents (Compose-observed state) so recomposition occurs
```
Comment (naderbahri) [inline app/src/main/java/com/swent/mapin/ui/map/MapScreen.kt]: **Nitpick**: The prior comment noted that Compose-observed savedEvents triggers recomposition. That hint can help future maintainers understand the data flow. Restore or expand on it briefly if that detail is still relevant.

File: app/src/main/java/com/swent/mapin/ui/map/MapScreen.kt [hunk 4]
```diff
@@ -567,10 +566,6 @@ fun MapScreen(
                       onRecentSearchClick = viewModel::applyRecentSearch,
                       onRecentEventClick = viewModel::onRecentEventClicked,
                       onClearRecentSearches = viewModel::clearRecentSearches,
-                      // I will fully remove topCategories in the next PR but started
-                      // with just MapScreenVm as i worked a lot on it
-                      topCategories = emptyList(),
-                      onCategoryClick = viewModel::applyRecentSearch,
```
Comment (naderbahri) [inline app/src/main/java/com/swent/mapin/ui/map/MapScreen.kt]: **Issue**: The call site removing topCategories clears a previous API path. Ensure all UI permutations driven by categories are validated visually or with instrumentation tests, or update the PR description to explain UI change rationale.

File: app/src/main/java/com/swent/mapin/model/event/EventRepositoryFirestore.kt [hunk 5]
```diff
@@ -561,18 +576,16 @@ class EventRepositoryFirestore(
...
    *
    * @param userId The user ID.
-   * @param source The source type (SAVED, JOINED, OWNED).
-   * @param onUpdate Callback with added, modified, and removed events.
-   * @return ListenerRegistration to manage the listener.
+   * @param source The source type (SAVED, JOINED, OWNED) field containing the list of IDs.
+   * @param onUpdate Callback to dispatch real-time changes: newly added, modified, or removed
+   *   events/IDs.
+   * @return ListenerRegistration composite object to unregister all attached listeners (user
+   *   listener and all event listeners).
```
[the remark this answers is not in the document]
Comment (e-bernier) [reply app/src/main/java/com/swent/mapin/model/event/EventRepositoryFirestore.kt]: There shouldn't be much logging in production code so it was part of the process of removing log of niche case that had already been tested and played with. But i can if you think it's safer really add them again.

File: app/src/main/java/com/swent/mapin/ui/map/eventstate/MapEventStateController.kt [hunk 6]
```diff
@@ -343,13 +370,29 @@ class MapEventStateController(
...
+    // Update modified events
+    modified.forEach { event -> currentMap[event.uid] = event }
+
+    // Remove deleted events
+    removedIds.forEach { id -> currentMap.remove(id) }
+
+    // Update state
+    _ownedEvents = currentMap.values.sortedByDescending { it.date }
+  }
+
```
[the remark this answers is not in the document]
Comment (e-bernier) [reply app/src/main/java/com/swent/mapin/ui/map/eventstate/MapEventStateController.kt]: _ownedEvents uses mutableStateOf from Compose, so the UI is automatically notified when it changes. I don't think there should be any problem here.

File: app/src/main/java/com/swent/mapin/model/event/EventRepository.kt (hunk 2 above)
Comment (e-bernier) [reply app/src/main/java/com/swent/mapin/model/event/EventRepository.kt]: Change done, hope it's clearer
