### PR TITLE
Add event capacity and bottom sheet filter fix

### LINKED ISSUE #538: Feature: Add optional capacity limit to events
Description: Add a "Max Capacity" field to the event creation screen to allow organizers to limit attendees.

Requirements:

- [x] Add an optional input field for capacity in the "Add Event" form.

- [x] Validate that the input is a positive integer.

- [x] Ensure the capacity value is passed correctly in the event payload

### PR DESCRIPTION
**Pull request by ziyad-elarroussi**
## Description
Add optional max capacity to event creation (validation, UI field, event payload) and include the bottom sheet gesture-bar fix so the filter section appears when expanding from collapsed to full.

**Related Issue:** closes #538

---

## Changes

**Implementation:**
- Add capacity input to Add Event form, validate positive integers, and pass through to event creation.
- Add capacity validation helper plus unit tests alongside price/tag utilities.
- Preserve bottom sheet fix that restores the filter section when transitioning from collapsed to full.

**Tests:**
- Added unit tests for capacity validation; other suites not run in this iteration.

---

## Testing
- [ ] Unit tests pass
- [ ] Instrumentation tests pass
- [ ] Manual testing completed
- [ ] Coverage maintained (≥80%)

**Test summary:** Added capacity validation unit tests; not run locally.

---

## Screenshots/Videos

---

## Checklist
- [ ] Sufficient documentation and minimal inline comments
- [ ] All tests passing
- [ ] No new warnings
- [ ] If related issue exists: issue has all labels, fields, and milestone filled

### CODE REVIEW

File: app/src/main/java/com/swent/mapin/ui/event/AddEventScreen.kt [hunk 1]
```diff
@@ -142,6 +146,7 @@ fun AddEventScreen(
   val time = remember { mutableStateOf("") }
   val endTime = remember { mutableStateOf("") }
   val price = remember { mutableStateOf("") }
+  val capacity = remember { mutableStateOf("") }
```
Comment (b10taj) [inline app/src/main/java/com/swent/mapin/ui/event/AddEventScreen.kt]: **Issue** : Manual addition of new field and error state (line 161) is correct but repetitive. Every new field will require edits in several places.
**Suggestion** : To improve scalability, consider using a data class for fields and a map for error states, reducing repetition and the risk of missing a place.

File: app/src/main/java/com/swent/mapin/ui/event/AddEventUtils.kt [hunk 2]
```diff
@@ -96,7 +108,8 @@ fun saveEvent(
     tags: List<String>,
     isPublic: Boolean,
     onDone: () -> Unit,
-    price: Double = 0.0
+    price: Double = 0.0,
+    capacity: Int? = null,
```
Comment (b10taj) [inline app/src/main/java/com/swent/mapin/ui/event/AddEventUtils.kt]: **Suggestion** :
Extension is correct, but ensure every saveEvent callsite throughout your codebase is updated accordingly to prevent runtime issues or accidental omissions.

File: app/src/main/java/com/swent/mapin/ui/map/BottomSheetContent.kt [hunk 3]
```diff
@@ -363,11 +363,9 @@ fun BottomSheetContent(
...
-                                      Modifier.fillMaxWidth()
-                                          .then(imePaddingModifier)
-                                          .verticalScroll(scrollState)
-                                  else Modifier.fillMaxWidth()
+                                  Modifier.fillMaxWidth()
+                                      .then(imePaddingModifier)
+                                      .verticalScroll(scrollState)
 
                               Column(modifier = contentModifier) {
                                 Spacer(modifier = Modifier.height(19.dp))
```
Comment (b10taj) [inline app/src/main/java/com/swent/mapin/ui/map/BottomSheetContent.kt]: **Suggestion**: Rendering filters unconditionally (relying on visual clipping for visibility) is generally safe in Jetpack Compose. However, ensure side effects like triggering data-fetch or recomposition of heavy children are not accidentally triggered when not visible

Other lines concerned : 475-486

**Review by b10taj — CHANGES_REQUESTED** [review]
These changes add support for an optional event capacity field in both the UI and underlying logic, including value validation, error reporting, resources, and test coverage. The implementation closely follows established validation and error handling patterns in existing code, keeping the approach consistent and understandable.

**Strengths** :

- Validation is robust and well-tested.
- UI/UX is consistent with the rest of the form.
- Code is readable and comprehensible.

**Areas for Improvement** :

- Scalability : Adding new field logic currently requires edits in many places; consider more data-driven patterns.
- Edge Cases: Upper bounds for capacity and user-facing feedback for parsing issues could be strengthened.
- Internationalization: New strings should be added to all supported locales.

Overall, the changes are well-constructed and functional, but some improvements could make the design more future-proof and user-friendly.

File: app/src/main/java/com/swent/mapin/ui/event/AddEventScreen.kt [hunk 4]
```diff
@@ -233,6 +241,7 @@ fun AddEventScreen(
                 endTimeError.value = endTime.value.isBlank()
                 tagError.value = !isValidTagInput(tag.value)
                 priceError.value = !isValidPriceInput(price.value)
+                capacityError.value = !isValidCapacityInput(capacity.value)
```
[the remark this answers is not in the document]
Comment (ziyad-elarroussi) [reply app/src/main/java/com/swent/mapin/ui/event/AddEventScreen.kt]: The new capacity validation/packing is only used in this   screen, and saveEvent has a default for capacity, so there are no other call sites to update today

File: app/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -17,6 +17,9 @@
     <string name="price_field">Price</string>
     <string name="price_text">Price (optional)</string>
     <string name="price_place_holder">Entry price:</string>
+    <string name="capacity_field">Capacity</string>
+    <string name="capacity_text">Maximum capacity (optional)</string>
+    <string name="capacity_place_holder">Max attendees:</string>
```
[the remark this answers is not in the document]
Comment (ziyad-elarroussi) [reply app/src/main/res/values/strings.xml]: There are no additional locale resource files beyond  values, so there are no translations to update

**Review by b10taj — APPROVED** [review]
The requested changes have been properly addressed. The new capacity field is now implemented in the Add Event screen, with corresponding validation logic, UI elements, updated utility functions, and string resources. Comprehensive unit tests have been added to cover capacity input validation. The modifications are well-structured and improve the overall flexibility and usability of event creation. Good job incorporating feedback!
